services:
  - type: cron
    name: telegram-signal-bot
    env: python
    schedule: "*/15 * * * *"  # Every 15 minutes
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
